language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - TESTER_PHP_BIN="php-cgi"
  - TESTER_PHP_BIN="php"

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - env: TESTER_PHP_BIN="php"

  include:
    - php: hhvm
      env: TESTER_PHP_BIN="php"

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

before_script:
  - ./libs/bin/parallel-lint -e php,phpt --exclude libs .

script:
  - ./libs/bin/tester -p $TESTER_PHP_BIN ./tests/
